app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::get('/acerca', function () {
    return view('acerca');
});

Route::auth();
/*
Route::resource('almacen/categoria','CategoriaController');
Route::resource('almacen/articulo','ItemController'); //'ArticuloController');
Route::resource('almacen/marca','MarcaController');
Route::resource('almacen/familia','FamiliaController');
Route::resource('almacen/modelo','ModeloController');
Route::resource('almacen/labor','LaborController');
Route::resource('asesor/vehiculo','VehiculoController');
Route::resource('ventas/cliente','ClienteController');
Route::resource('ventas/venta','VentaController');
Route::resource('compras/proveedor','ProveedorController');
Route::resource('compras/ingreso','IngresoController');
Route::resource('seguridad/usuario','UsuarioController');
Route::resource('hr/position','PositionController');
Route::resource('configuracion/uom','UomController');

// personal
Route::group(['prefix' => 'hr'], function () {
    Route::post('/personal/{flag}', 'PersonalController@index')->name('all');
    Route::resource('personal', 'PersonalController');
});

Route::get('excel',  'PersonalController@export')->name('export');



//Vehiculos
Route::group(['prefix' => 'asesor'], function () {
    Route::resource('vehiculo', 'VehiculoController');
});
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'VehiculoController@selectAjax']);

Route::get('excelvehiculos',  'VehiculoController@export')->name('exportvehiculos');


// Cliente
Route::group(['prefix' => 'ventas'], function () {
    Route::post('/cliente/{flag}', 'ClienteController@index')->name('all');
    Route::resource('cliente', 'ClienteController');
});
Route::get('excel2',  'ClienteController@export')->name('exportCliente');
// FIN Cliente

// proveedor
Route::group(['prefix' => 'compras'], function () {
    Route::post('/proveedor/{flag}', 'ProveedorController@index')->name('all');
    Route::resource('proveedor', 'ProveedorController');
});
Route::get('excel3',  'ProveedorController@export')->name('exportvendor');
// FIN proveedor
 
// organizacion

Route::get('/home', 'HomeController@index');

Route::resource('organizacion', 'OrganizacionController');

Route::get('configuracion/organizacion', 'OrganizacionController@index');

Route::get('configuracion/organizacion/create', 'OrganizacionController@create');

Route::post('configuracion/organizacion/store', 'OrganizacionController@store');

Route::post('configuracion/organizacion/update', 'OrganizacionController@update');

Route::get('/reporteorganizacion', 'OrganizacionController@reporte');

Route::get('/home', 'HomeController@index');


// fndlookup

Route::resource('fndlookup', 'FndLookupController');

Route::get('configuracion/fndlookup', 'FndLookupController@index');

Route::get('configuracion/fndlookup/create', 'FndLookupController@create');

Route::post('configuracion/fndlookup/store', 'FndLookupController@store');

Route::post('configuracion/fndlookup/update', 'FndLookupController@update');

Route::get('configuracion/destroy_fndlookup/{id}', 'FndLookupController@destroy');

Route::get('/activar_fndlookup/{id}', 'FndLookupController@activar');

Route::get('/reportefndlookup', 'FndLookupController@reporte');

Route::get('/ajax_edit_lookup', 'FndLookupValueController@ajax_edit_lookup');


// labor

Route::resource('labor', 'LaborController');

Route::get('almacen/labor', 'LaborController@index');

Route::get('almacen/labor/create', 'LaborController@create');

Route::post('almacen/labor/store', 'LaborController@store');

Route::post('almacen/labor/update', 'LaborController@update');

Route::get('almacen/destroy_labor/{id}', 'LaborController@destroy');

Route::get('almacen/activar_labor/{id}', 'LaborController@activar');

Route::get('reportelabor', 'LaborController@reporte');

Route::get('ajax_edit_labor', 'LabormmaController@ajax_edit_labor');


// subinventario

Route::resource('subinventario', 'SubInventarioController');

Route::get('almacen/subinventario', 'SubInventarioController@index');

Route::get('almacen/subinventario/create', 'SubInventarioController@create');

Route::post('almacen/subinventario/store', 'SubInventarioController@store');

Route::post('almacen/subinventario/update', 'SubInventarioController@update');

Route::get('almacen/destroy_subinventario/{id}', 'SubInventarioController@destroy');

Route::get('almacen/activar_subinventario/{id}', 'SubInventarioController@activar');

Route::get('reportesubinventario', 'SubInventarioController@reporte');

Route::get('/ajax_edit_subinventario', 'SubInventarioController@ajax_edit_subinventario');

// Ajax validacion




Route::get('ajax_modelos', 'LaborController@ajax_modelo');

Route::get('ajax_validacion', 'OrganizacionController@validationall');

Route::get('ajax_validacion_update', 'OrganizacionController@validationallupdate');

Route::get('ajax_validad_marca', 'LaborController@ajax_validad_marca');

Route::get('ajax_guardar_marca', 'LabormmaController@store');

Route::get('eliminar_marca', 'LabormmaController@destroy');

Route::get('/ajax_labor_eliminar', 'LaborController@destroy');

Route::get('/ajax_labor_activar', 'LaborController@activar');

Route::get('/ajax_lookup_eliminar', 'FndLookupController@destroy');

Route::get('/ajax_lookup_activar', 'FndLookupController@activar');

Route::get('/guardar_lookup_value', 'FndLookupValueController@store');

Route::get('/eliminar_lookup_value', 'FndLookupValueController@destroy');

Route::get('/ajax_sub_inventario_destroy', 'SubInventarioController@destroy');

Route::get('/ajax_sub_inventario_activar', 'SubInventarioController@activar');



//Reportes
Route::get('reportecategorias', 'CategoriaController@reporte');
Route::get('reportemarcas', 'MarcaController@reporte');
Route::get('reportemodelos', 'ModeloController@reporte');
Route::get('reportefamilias', 'FamiliaController@reporte');
Route::get('reportearticulos', 'ArticuloController@reporte');
Route::get('reporteclientes', 'ClienteController@reporte');
Route::get('reporteproveedores', 'ProveedorController@reporte');
Route::get('reporteventas', 'VentaController@reporte');
Route::get('reporteventa/{id}', 'VentaController@reportec');
Route::get('reporteingresos', 'IngresoController@reporte'); 
Route::get('reporteingreso/{id}', 'IngresoController@reportec'); 
*/

Route::get('/{slug?}', 'HomeController@index');

//JP
Route::group(['prefix' => 'ventas'], function()
{
	//Facturas
	Route::resource('factura', 'FacturaController'); 
	Route::get('factura/delete/{factura}', ['as' => 'ventas.factura.delete', 'uses' => 'FacturaController@delete']);
	Route::get('factura/cancel/{factura}', ['as' => 'ventas.factura.cancel', 'uses' => 'FacturaController@cancel']);
	Route::post('cancelFactura/{factura}', ['as' => 'ventas.recibo.setCancel', 'uses' => 'FacturaController@setCancel']);

	//Recibos
	Route::resource('recibo', 'ReciboController'); 
	Route::get('recibo/delete/{recibo}', ['as' => 'ventas.recibo.delete', 'uses' => 'ReciboController@delete']);
	Route::get('recibo/reverse/{recibo}', ['as' => 'ventas.recibo.reverse', 'uses' => 'ReciboController@reverse']);
	Route::post('reverseRecibo/{recibo}', ['as' => 'ventas.recibo.setReverse', 'uses' => 'ReciboController@setReverse']);

	//ReciboDetalle
	Route::post('reciboDetalle', ['as' => 'ventas.recibo.detalle.store', 'uses' => 'ReciboDetalleController@store']);
	Route::get('reciboDetalle/{recibo}', ['as' => 'ventas.recibo.detalle.show', 'uses' => 'ReciboDetalleController@show']);

	//Articulos
	Route::get('item/{item}', ['as' => 'ventas.item.show', 'uses' => 'ItemController@showFA']);
	Route::get('item', ['as' => 'ventas.item.index', 'uses' => 'ItemController@indexFA']);	

	//FacturaDetalle
	Route::post('facturaDetalle', ['as' => 'ventas.factura.detalle.store', 'uses' => 'FacturaDetalleController@store']);
	Route::get('facturaDetalle/{factura}', ['as' => 'ventas.factura.detalle.show', 'uses' => 'FacturaDetalleController@show']);	

	//Impuestos
	Route::get('tax/{tax}', ['as' => 'ventas.tax', 'uses' => 'ImpuestoController@show']);
	Route::get('tax', ['as' => 'ventas.tax', 'uses' => 'ImpuestoController@index']);

	//Unidad de medida
	Route::get('item/uom/{item}', ['as' => 'ventas.item.uom', 'uses' => 'UomController@show']);
	
	//Clientes
	Route::get('clienteFa/', ['as' => 'ventas.cliente.api', 'uses' => 'ClienteController@showApi']);
	Route::get('clienteFa/{cliente}', ['as' => 'ventas.cliente.factura', 'uses' => 'ClienteController@pendingBills']);

	Route::get('create/plazo/{factura}', ['as' => 'ventas.plazo.create', 'uses' => 'PlazoController@create']);	
	Route::get('plazo/{factura}', ['as' => 'ventas.plazo.show', 'uses' => 'PlazoController@show']);	
	
	Route::post('plazo', ['as' => 'ventas.plazo.store', 'uses' => 'PlazoController@store']);	
});

Route::resource('almacen/warehouse', 'WarehouseController');

Route::get('userSite/user', [ 'as' => 'userSite.user', 'uses' => 'UserSiteController@userList']);
Route::get('userSite/site', [ 'as' => 'userSite.site', 'uses' => 'UserSiteController@siteList']);
Route::get('emailSite/{email}', ['as' => 'emailSite.user', 'uses' => 'UserSiteController@emailSite']);

Route::resource('seguridad/usersite', 'UserSiteController');

Route::get('password/email', 'Auth\PasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');

Route::resource('compras/orden', 'OrdenController');
Route::resource('compras/poDetail', 'PurchaseOrderDetailController');
Route::get('compras/cancelOrden/{order}', 'OrdenController@cancel');

app/Caja.php
<?php

namespace sisVentas;

use Illuminate\Database\Eloquent\Model;
use sisVentas\Cajero;
use sisVentas\FndLookupValue;
use sisVentas\Site;

class Caja extends Model
{
    protected $table = 'pos_op_amt';

    protected $primaryKey = 'idopamt';

    protected $fillable = ['site_id', 'idcashier', 'start_date', 'end_date', 'start_amount', 'comment', 'rate', 'barcode_reader', 'rate_date', 'created_by',];

    //relationships
    public function pos()
    {
    	return $this->hasMany(Pos::class, 'pos_op_amt_id', 'idopamt');
    }

    public function cashier()
    {
        return $this->belongsTo(Cajero::class, 'idcashier', 'id');
    }

    public function site()
    {
        return $this->belongsTo(Site::class);
    }


    public function sells()
    {
        $sells = [];
        $change = 0;
        foreach (FndLookupValue::all() as $pay_type) {
            $amount = 0;
            $count = 0;
            foreach ($this->pos as $pos) {
                $pay = $pos->posPay->where('type_lookup_code', $pay_type->code_value)->sum('amount');
                $amount += $pay;
                $count += $pay > 0 ? 1 : 0;
            }          


            if ($amount > 0) {                
                array_push($sells, [
                    $pay_type->description . " ($count)" => $amount
                ]);
            }
        }

        foreach ($this->pos as $pos) {
            $change += $pos->change;
        }    

        if ($change > 0){
            array_push($sells, [
                'Vueltos' => $change * -1,
            ]);            
        }

        return $sells;        
    }

    public function getPaysTotalAttribute()
    {
        $total = 0;
        foreach ($this->pos as $pos) {
            $total += $pos->posPay->sum('amount') - (isset($pos->change) ? $pos->change : 0);
        }   

        return $total;     

    }    

    public function getSellsTotalAttribute()
    {
        $total = 0;
        foreach ($this->pos as $pos) {
            $total += $pos->posDetail->sum('price') * $pos->posDetail->sum('quantity');
        }   

        return $total;     

    }

    public function getTotalAttribute()
    {
        $total = 0;
        foreach ($this->pos as $pos) {
            foreach ($pos->posDetail as $detail) {
                $disccount = $detail->price * $detail->item_disccount;
                
                $tax = (($detail->price - $disccount)  * $detail->quantity) * $detail->tax_rate / 100;

                $total += (($detail->price - $disccount) * $detail->quantity) + $tax;               
            }
        }   

        return $total;     

    }    

    public function getCashierNameAttribute()
    {       
        return $this->cashier->name;
    }

    public function getSiteNameAttribute()
    {       
        return $this->site->name;
    }    
}

app/Http/Controllers/CajaController.php
<?php

namespace sisVentas\Http\Controllers;

use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use sisVentas\Caja;
use sisVentas\Http\Requests;

class CajaController extends Controller
{
    public function index()
    {
        $cashes = Caja::where('site_id', Session::get('site_id'))->paginate();

        return view('ventas.caja.index', compact('cashes'));
    }

    public function show($id)
    {
        $cash = Caja::find($id);

        return view('ventas.caja.edit', compact('cash'));
    }

    public function open()
    {
        //dd(request()->all());
        $caja = Caja::create(request()->all());
        $caja->site_id = Session::get('site_id');
        $caja->created_by = auth()->user()->id;
        $caja->last_updated_by = auth()->user()->id;
        $caja->start_date = $caja->created_at;
        if (request()->idcashier == null)
        {
            $caja->idcashier = auth()->user()->cashier->id;
        }
        $caja->save();

        return [
            'message' => 'Caja abierta satisfactoriamente', 
            'cash_id' => $caja->idopamt
        ];
    }

    public function close($id)
    {
        $caja = Caja::find($id);
        $caja->end_date = Carbon::now();
        $caja->last_updated_by = auth()->user()->id;
        $caja->save();

        return ['message' => 'Caja cerrada satisfactoriamente'];
    }

}

resources/views/ventas/caja/edit.blade.php
@extends ('layouts.admin')
@section ('contenido')
<div v-cloak class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

	<div class="box box-solid box-primary">
	  <div class="box-header with-border">
	    <h3 class="box-title">Cerrar Caja {{$cash->idopamt}}</h3>
	    <input type="hidden" ref="cash_id" value="{{$cash->idopamt}}">
	    <div class="box-tools pull-right">
	      <!-- Buttons, labels, and many other things can be placed here! -->
	      <!-- Here is a label for example -->
	      <span class="label label-success">Label</span>
	    </div>
	  </div>
	  <div class="box-body">
		<table class="table">
			<tr class="active">
				<th><h4>Resumen de Ventas</h4></th>
				<th class="text-right"><h4>{{number_format($cash->pays_total, 2)}}</h4></th>
			</tr>
			@foreach($cash->sells() as $sell)
			<tr>
				<th>{{key($sell)}}</th>
				<td class="text-right">{{number_format($sell[key($sell)], 2)}}</td>
			</tr>
			@endforeach
		</table>

	  </div>

	  <div class="box-footer">
	  	<div class="pull-right">	  		
	    <a class="btn btn-danger" href="/ventas/cash">Volver</a>
	    @if(!isset($cash->end_date))
	    	<button class="btn btn-success" v-if="!closed" @click="close">Cerrar Caja</button>	  	
	    @endif
	  	</div>
	  </div>
	</div>	

	</div>	
</div>

@endsection

@section('js')
	<script>
		var app = new Vue({
			el: '#app',
			data: function(){
				return{
					closed: false,
				}
			},

			methods:{
				close: function(){
					var answer = confirm("Seguro que desea cerrar la caja?")
					if (answer) {
						var self = this;
						axios.put('/ventas/closeCash/' + this.$refs.cash_id.value)
							.then(function(response){
								alert(response.data.message);
								self.closed = true;
							})
							.catch(function(error){
								alert(error);
							});
					    //some code
					}
				
				}
			},
		});
	</script>
@endsection

resources/views/ventas/caja/index.blade.php
@extends ('layouts.admin')
@section ('contenido')

<div class="box box-solid box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Listado de cajas</h3>
    <div class="box-tools pull-right">
      <button class="btn btn-success" data-toggle="modal" data-target="#modalCash" @click="getVendors">Abrir Caja</button>
    </div>
  </div>
  <div class="box-body">
	{{-- Search --}}
  </div>



<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-condensed table-hover">
				<thead>
					<th>Almacen</th>
					<th>Vendedor</th>
					<th>Saldo inicial</th>
					<th>Vendido</th>
          <th>Fecha de apertura</th>
					<th>Fecha de cierre</th>
					<th>Acciones</th>
				</thead>
				@foreach ($cashes as $cash)
				<tr>
					<td>{{ $cash->site_name}}</td>
					<td>{{ isset($cash->cashier_name) ? $cash->cashier_name : '' }}</td>
					<td>{{ number_format($cash->start_amount, 2)}}</td>			
					<td>{{ number_format($cash->total, 2)}}</td>			
                    <td>{{ date_format(date_create($cash->start_date),"d-m-Y H:i:s")}}</td>
                    <td>{{ isset($cash->end_date) ? date_format(date_create($cash->end_date),"d-m-Y H:i:s") : ''}}</td>                    
					<td>
                        @if(isset($cash->end_date))
                        <a class="btn btn-info btn-xs" role="button" href="{{url('ventas/cash/' . $cash->idopamt)}}">
                            <i class="fa fa-eye" aria-hidden="true"></i>
                        </a> 
                        @else                                
						<a class="btn btn-danger btn-xs" role="button" href="{{url('ventas/cash/' . $cash->idopamt)}}">
                            <i class="fa fa-close" aria-hidden="true"></i>
                        </a>  
                        @endif                   			
					</td>
				</tr>
				@endforeach
				@include('ventas.caja.partials.cash')
			</table>
		</div>
		<div class="text-center">
			{{$cashes->render()}}			
		</div>
	</div>
</div>
</div>
@endsection