app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('auth/login');
});
Route::get('/acerca', function () {
    return view('acerca');
});

Route::auth();
/*
Route::resource('almacen/categoria','CategoriaController');
Route::resource('almacen/articulo','ItemController'); //'ArticuloController');
Route::resource('almacen/marca','MarcaController');
Route::resource('almacen/familia','FamiliaController');
Route::resource('almacen/modelo','ModeloController');
Route::resource('almacen/labor','LaborController');
Route::resource('asesor/vehiculo','VehiculoController');
Route::resource('ventas/cliente','ClienteController');
Route::resource('ventas/venta','VentaController');
Route::resource('compras/proveedor','ProveedorController');
Route::resource('compras/ingreso','IngresoController');
Route::resource('seguridad/usuario','UsuarioController');
Route::resource('hr/position','PositionController');
Route::resource('configuracion/uom','UomController');

// personal
Route::group(['prefix' => 'hr'], function () {
    Route::post('/personal/{flag}', 'PersonalController@index')->name('all');
    Route::resource('personal', 'PersonalController');
});

Route::get('excel',  'PersonalController@export')->name('export');



//Vehiculos
Route::group(['prefix' => 'asesor'], function () {
    Route::resource('vehiculo', 'VehiculoController');
});
Route::post('select-ajax', ['as'=>'select-ajax','uses'=>'VehiculoController@selectAjax']);

Route::get('excelvehiculos',  'VehiculoController@export')->name('exportvehiculos');


// Cliente
Route::group(['prefix' => 'ventas'], function () {
    Route::post('/cliente/{flag}', 'ClienteController@index')->name('all');
    Route::resource('cliente', 'ClienteController');
});
Route::get('excel2',  'ClienteController@export')->name('exportCliente');
// FIN Cliente

// proveedor
Route::group(['prefix' => 'compras'], function () {
    Route::post('/proveedor/{flag}', 'ProveedorController@index')->name('all');
    Route::resource('proveedor', 'ProveedorController');
});
Route::get('excel3',  'ProveedorController@export')->name('exportvendor');
// FIN proveedor
 
// organizacion

Route::get('/home', 'HomeController@index');

Route::resource('organizacion', 'OrganizacionController');

Route::get('configuracion/organizacion', 'OrganizacionController@index');

Route::get('configuracion/organizacion/create', 'OrganizacionController@create');

Route::post('configuracion/organizacion/store', 'OrganizacionController@store');

Route::post('configuracion/organizacion/update', 'OrganizacionController@update');

Route::get('/reporteorganizacion', 'OrganizacionController@reporte');

Route::get('/home', 'HomeController@index');


// fndlookup

Route::resource('fndlookup', 'FndLookupController');

Route::get('configuracion/fndlookup', 'FndLookupController@index');

Route::get('configuracion/fndlookup/create', 'FndLookupController@create');

Route::post('configuracion/fndlookup/store', 'FndLookupController@store');

Route::post('configuracion/fndlookup/update', 'FndLookupController@update');

Route::get('configuracion/destroy_fndlookup/{id}', 'FndLookupController@destroy');

Route::get('/activar_fndlookup/{id}', 'FndLookupController@activar');

Route::get('/reportefndlookup', 'FndLookupController@reporte');

Route::get('/ajax_edit_lookup', 'FndLookupValueController@ajax_edit_lookup');


// labor

Route::resource('labor', 'LaborController');

Route::get('almacen/labor', 'LaborController@index');

Route::get('almacen/labor/create', 'LaborController@create');

Route::post('almacen/labor/store', 'LaborController@store');

Route::post('almacen/labor/update', 'LaborController@update');

Route::get('almacen/destroy_labor/{id}', 'LaborController@destroy');

Route::get('almacen/activar_labor/{id}', 'LaborController@activar');

Route::get('reportelabor', 'LaborController@reporte');

Route::get('ajax_edit_labor', 'LabormmaController@ajax_edit_labor');


// subinventario

Route::resource('subinventario', 'SubInventarioController');

Route::get('almacen/subinventario', 'SubInventarioController@index');

Route::get('almacen/subinventario/create', 'SubInventarioController@create');

Route::post('almacen/subinventario/store', 'SubInventarioController@store');

Route::post('almacen/subinventario/update', 'SubInventarioController@update');

Route::get('almacen/destroy_subinventario/{id}', 'SubInventarioController@destroy');

Route::get('almacen/activar_subinventario/{id}', 'SubInventarioController@activar');

Route::get('reportesubinventario', 'SubInventarioController@reporte');

Route::get('/ajax_edit_subinventario', 'SubInventarioController@ajax_edit_subinventario');

// Ajax validacion




Route::get('ajax_modelos', 'LaborController@ajax_modelo');

Route::get('ajax_validacion', 'OrganizacionController@validationall');

Route::get('ajax_validacion_update', 'OrganizacionController@validationallupdate');

Route::get('ajax_validad_marca', 'LaborController@ajax_validad_marca');

Route::get('ajax_guardar_marca', 'LabormmaController@store');

Route::get('eliminar_marca', 'LabormmaController@destroy');

Route::get('/ajax_labor_eliminar', 'LaborController@destroy');

Route::get('/ajax_labor_activar', 'LaborController@activar');

Route::get('/ajax_lookup_eliminar', 'FndLookupController@destroy');

Route::get('/ajax_lookup_activar', 'FndLookupController@activar');

Route::get('/guardar_lookup_value', 'FndLookupValueController@store');

Route::get('/eliminar_lookup_value', 'FndLookupValueController@destroy');

Route::get('/ajax_sub_inventario_destroy', 'SubInventarioController@destroy');

Route::get('/ajax_sub_inventario_activar', 'SubInventarioController@activar');



//Reportes
Route::get('reportecategorias', 'CategoriaController@reporte');
Route::get('reportemarcas', 'MarcaController@reporte');
Route::get('reportemodelos', 'ModeloController@reporte');
Route::get('reportefamilias', 'FamiliaController@reporte');
Route::get('reportearticulos', 'ArticuloController@reporte');
Route::get('reporteclientes', 'ClienteController@reporte');
Route::get('reporteproveedores', 'ProveedorController@reporte');
Route::get('reporteventas', 'VentaController@reporte');
Route::get('reporteventa/{id}', 'VentaController@reportec');
Route::get('reporteingresos', 'IngresoController@reporte'); 
Route::get('reporteingreso/{id}', 'IngresoController@reportec'); 
*/

Route::get('/{slug?}', 'HomeController@index');

//JP
Route::group(['prefix' => 'ventas'], function()
{
	//Facturas
	Route::resource('factura', 'FacturaController'); 
	Route::get('factura/delete/{factura}', ['as' => 'ventas.factura.delete', 'uses' => 'FacturaController@delete']);
	Route::get('factura/cancel/{factura}', ['as' => 'ventas.factura.cancel', 'uses' => 'FacturaController@cancel']);
	Route::post('cancelFactura/{factura}', ['as' => 'ventas.recibo.setCancel', 'uses' => 'FacturaController@setCancel']);

	//Recibos
	Route::resource('recibo', 'ReciboController'); 
	Route::get('recibo/delete/{recibo}', ['as' => 'ventas.recibo.delete', 'uses' => 'ReciboController@delete']);
	Route::get('recibo/reverse/{recibo}', ['as' => 'ventas.recibo.reverse', 'uses' => 'ReciboController@reverse']);
	Route::post('reverseRecibo/{recibo}', ['as' => 'ventas.recibo.setReverse', 'uses' => 'ReciboController@setReverse']);

	//ReciboDetalle
	Route::post('reciboDetalle', ['as' => 'ventas.recibo.detalle.store', 'uses' => 'ReciboDetalleController@store']);
	Route::get('reciboDetalle/{recibo}', ['as' => 'ventas.recibo.detalle.show', 'uses' => 'ReciboDetalleController@show']);

	//Articulos
	Route::get('item/{item}', ['as' => 'ventas.item.show', 'uses' => 'ItemController@showFA']);
	Route::get('item', ['as' => 'ventas.item.index', 'uses' => 'ItemController@indexFA']);	

	//FacturaDetalle
	Route::post('facturaDetalle', ['as' => 'ventas.factura.detalle.store', 'uses' => 'FacturaDetalleController@store']);
	Route::get('facturaDetalle/{factura}', ['as' => 'ventas.factura.detalle.show', 'uses' => 'FacturaDetalleController@show']);	

	//Impuestos
	Route::get('tax/{tax}', ['as' => 'ventas.tax', 'uses' => 'ImpuestoController@show']);
	Route::get('tax', ['as' => 'ventas.tax', 'uses' => 'ImpuestoController@index']);

	//Unidad de medida
	Route::get('item/uom/{item}', ['as' => 'ventas.item.uom', 'uses' => 'UomController@show']);
	
	//Clientes
	Route::get('clienteFa/', ['as' => 'ventas.cliente.api', 'uses' => 'ClienteController@showApi']);
	Route::get('clienteFa/{cliente}', ['as' => 'ventas.cliente.factura', 'uses' => 'ClienteController@pendingBills']);

	Route::get('create/plazo/{factura}', ['as' => 'ventas.plazo.create', 'uses' => 'PlazoController@create']);	
	Route::get('plazo/{factura}', ['as' => 'ventas.plazo.show', 'uses' => 'PlazoController@show']);	
	
	Route::post('plazo', ['as' => 'ventas.plazo.store', 'uses' => 'PlazoController@store']);	
});

Route::resource('almacen/warehouse', 'WarehouseController');

Route::get('userSite/user', [ 'as' => 'userSite.user', 'uses' => 'UserSiteController@userList']);
Route::get('userSite/site', [ 'as' => 'userSite.site', 'uses' => 'UserSiteController@siteList']);
Route::get('emailSite/{email}', ['as' => 'emailSite.user', 'uses' => 'UserSiteController@emailSite']);

Route::resource('seguridad/usersite', 'UserSiteController');

Route::get('password/email', 'Auth\PasswordController@showLinkRequestForm');
Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');

Route::resource('compras/orden', 'OrdenController');
Route::resource('compras/poDetail', 'PurchaseOrderDetailController');
Route::get('compras/cancelOrden/{order}', 'OrdenController@cancel');

app/Factura.php
<?php

namespace sisVentas;

use Illuminate\Database\Eloquent\Model;

class Factura extends Model
{
      protected $table = 'cc_customer_trx_all';

      protected $primaryKey='customer_trx_id';

      protected $fillable = [
            'customer_trx_id',
            'trx_number',
            'class_code',
            'class_trx',
            'cust_trx_type_id',
            'trx_date',
            'bill_to_contact_id',
            'bill_to_contact',
            'source_code',
            'bill_to_customer_id',
            'ship_to_customer_id',
            'ship_to_contact',
            'ship_to_contact_id',
            'shipment_id',
            'remit_to_address_id',
            'term_id',
            'term_due_date',
            'salesrep_id',
            'purchase_order',
            'purchase_order_revision',
            'purchase_order_date',
            'comments',
            'exchange_rate_type',
            'exchange_date',
            'exchange_rate',
            'invoice_currency_code',
            'complete_flag',
            'bill_to_address_id',
            'ship_to_address_id',
            'receipt_method_id',
            'status_trx',
            'doc_sequence_id',
            'doc_sequence_value',
          ];

      //Relationship
      public function clientToBill()
      {
            return $this->belongsTo('\sisVentas\Cliente', 'bill_to_customer_id', 'idcliente');
      }

      public function billCurrency()
      {
            return $this->belongsTo('\sisVentas\Moneda', 'invoice_currency_code', 'currency_code');        
      }

      public function detail()
      {
        return $this->hasMany(FacturaDetalle::class, 'customer_trx_id', 'customer_trx_id');
      }

      public function receipts()
      {
        return $this->hasMany(ReciboDetalle::class, 'customer_trx_id', 'customer_trx_id');
      }

      public function terms()
      {
        return $this->hasMany('\sisVentas\Plazo', 'customer_trx_id', 'customer_trx_id');
      }

      //Attributes

      public function getAmountAttribute()      
      {
        $total = 0;
      
        foreach ($this->detail()->get()->toArray() as $detail) {
        $total += $detail['quantity_ordered'] * $detail['unit_selling_price'];
        }
      
        return round($total + $this->tax, 2); 
      }

      public function getTaxAttribute()      
      {
        $total = 0;
      
        foreach ($this->detail()->with('tax')->get()->toArray() as $detail) {
          $total += $detail['quantity_ordered'] * $detail['unit_selling_price'] * ($detail['tax']['tax_rate']/100);
        }
      
        return $total;
      }      

      public function getReceiptsAppliedAttribute()
      {

            return $this->receipts->sum('amount_applied') + $this->receipts->sum('discount_original');
      }      


      public function getBalanceAttribute()
      {
          $saldo = $this->amount - $this->receiptsApplied;
            return ($saldo < 0.01 && $saldo > -0.1) ? 0 : $saldo;
      }      

      public function getIdAttribute()
      {
            return $this->customer_trx_id;
      }

      public function getBillToAttribute()
      {
             return  "{$this->clientToBill->first_name} {$this->clientToBill->first_last_name}";
      }

      public function getCurrencyAttribute()
      {
             return "{$this->clientToBill->first_name} {$this->clientToBill->first_last_name}";
      }    

      public function getIsClosedAttribute()
      {
        return $this->amount > 0 && $this->balance == 0;
      }  

      public function getIsCompletedAttribute()
      {
        return $this->complete_flag == 'Y';
      }  

      //Scopes

      public function scopeId($query,  $start, $end)
      {
          if ($start != '' && $end == '')
              $query->where('trx_number', $start);
      }

      public function scopeIdClient($query, $id)
      {
          if ($id != "" and is_numeric($id))
              $query->where('bill_to_customer_id', $id);
      }      

      public function scopeClient($query, $name)
      {
          if ($name != "" and !is_numeric($name)){
              $users = Cliente::where('first_name', 'LIKE', "%$name%")
                ->orWhere('first_last_name', 'LIKE', "%$name%")
                ->get();
              //dd($users);

              $query->whereIn('bill_to_customer_id', $users->pluck('idcliente'));
          }
      }

      public function scopeIdRange($query, $start, $end)
      {
        if ($start != '' && $end != '') {
              $query->whereBetween('trx_number', [$start, $end]);
        }
      }

      public function scopeDateRange($query, $start, $end)
      {
        if ($start != '' && $end != '') {
              $query->whereBetween('trx_date', [$start, $end]);
        }
      }     

}

resources/views/ventas/factura/cancel.blade.php
@extends ('layouts.admin')
@section ('contenido')
<div class="col-md-6 col-md-offset-3">
	<div class="info-box">

	  <span class="info-box-icon bg-red"><i class="fa fa-trash"></i></span>
	  <div class="info-box-content">
	    <span class="info-box-text"><h3>Cancelar Factura {{$bill->trx_number}} </h3></span>
	    <span class="info-box-number">¿Seguro que desea cancelar la factura  {{$bill->trx_number}}?</span>
	    <hr>
	    {!!Form::open(['url'=>'/ventas/cancelFactura/' . $bill->customer_trx_id,'method'=>'POST','autocomplete'=>'off', 'class' => ''])!!}
		    <button type="submit" class="btn btn-danger">Aceptar</button>
		    <a href="/ventas/factura"> <button class="btn btn-success">Cancelar</button></a>
	    {!!Form::close()!!}	
	  </div>

	</div>	
</div>

@endsection

resources/views/ventas/factura/create.blade.php
@extends ('layouts.admin')
@section ('contenido')

	<div v-cloak class="row">	
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <h3>Nueva Factura</h3>
                @if (count($errors)>0)
                <div class="alert alert-danger">
                <ul>
                @foreach ($errors->all() as $error)
                	<li>{{$error}}</li>
                @endforeach
                </ul>
                </div>
                @endif

                {!!Form::open(['url'=>'ventas/factura','method'=>'POST','autocomplete'=>'off'])!!}
                {{Form::token()}}

                    @include('ventas.factura.partials.fields')                  	                       
                   
                  <div class="form-group">
                    <button class="btn btn-primary" type="submit" @click="setHiddens">Finalizar</button>
                    <a class="btn btn-danger" href="{{url('ventas/factura')}}">Cancelar</a>
                  </div>

                {!!Form::close()!!}		

                </div>
	</div>
    @include('ventas.factura.partials.message')
    
@endsection

@section('js')
<script src="{{asset('js/bills.js')}}"></script>

    <script>
        $(".inputmask1").inputmask("(999) 9999999");
        $(".inputmask2").inputmask("(999) 999999999");
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "es",
            autoclose: true,
            viewMode: 'years'
        });

    </script>

@endsection

resources/views/ventas/factura/delete.blade.php
@extends ('layouts.admin')
@section ('contenido')
<div class="col-md-6 col-md-offset-3">
	<div class="info-box">

	  <span class="info-box-icon bg-red"><i class="fa fa-trash"></i></span>
	  <div class="info-box-content">
	    <span class="info-box-text"><h3>Eliminar Factura {{$bill->trx_number}} </h3></span>
	    <span class="info-box-number">¿Seguro que desea eliminar la factura  {{$bill->trx_number}}?</span>
	    <hr>
	    {!!Form::open(['url'=>'/ventas/factura/' . $bill->customer_trx_id,'method'=>'DELETE','autocomplete'=>'off', 'class' => ''])!!}
		    <button type="submit" class="btn btn-danger">Aceptar</button>
		    <a href="/ventas/factura"> <button class="btn btn-success">Cancelar</button></a>
	    {!!Form::close()!!}	
	  </div>

	</div>	
</div>

@endsection

resources/views/ventas/factura/edit.blade.php
@extends ('layouts.admin')
@section ('contenido')
<div v-cloak class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<h3>Editar Factura: {{ $bill->trx_number }}</h3>

		@if (count($errors)>0)
		<div class="alert alert-danger">
			<ul>
			@foreach ($errors->all() as $error)
				<li>{{$error}}</li>
			@endforeach
			</ul>
		</div>
		@endif

		{!!Form::open(['url'=>'ventas/factura/' . $bill->customer_trx_id,'method'=>'PUT','autocomplete'=>'off', 'class' => ''])!!}
		{{Form::token()}}
			@include('ventas.factura.partials.fields')	             
	            <div class="form-group">
	            	@if(!$bill->isClosed)
	            		<button class="btn btn-primary" type="submit" @click="setHiddens" :disabled="isCompleted">Guardar</button>
	            	@endif
	            		<a class="btn btn-danger" href="{{url('ventas/factura')}}">Cancelar</a>
				<button type="button" class="btn btn-success" data-toggle="modal" data-target="#detailModal">Articulos lineas <span class="badge">@{{items.length}}</span></button>

	            </div>

		{!!Form::close()!!}		
	</div>
	@include('ventas.factura.partials.detalle')
	@include('ventas.recibo.partials.message')
</div>

@endsection

@section('js')
    <script src="{{asset('js/bills.js')}}"></script>
    <script>
        $(".inputmask1").inputmask("(999) 9999999");
        $(".inputmask2").inputmask("(999) 999999999");
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "es",
            autoclose: true,
            viewMode: 'years'
        });

    </script>
@endsection

resources/views/ventas/factura/index.blade.php
@extends ('layouts.admin')
@section ('contenido')

<div class="box box-solid box-primary">
  <div class="box-header with-border">
    <h3 class="box-title">Listado de Facturas</h3>
    <div class="box-tools pull-right">
      <a href="/ventas/factura/create"><button class="btn btn-success">Nueva factura</button></a></h3>
    </div>
  </div>
  <div class="box-body">
	@include('ventas.factura.partials.search')
  </div>

</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<div class="table-responsive">
			<table class="table table-striped table-bordered table-condensed table-hover">
				<thead>
					<th>Nro Documento</th>
					<th>Cliente</th>
					<th>Total a Pagar</th>
					<th>Saldo</th>
					<th>Fecha</th>
				</thead>
               @foreach ($bills as $bill)
				<tr>
					<td>{{ $bill->trx_number}}</td>
					<td>{{ $bill->bill_to}}</td>
					<td>{{ number_format($bill->amount, 2)}}</td>
					<td>{{ number_format($bill->balance, 2)}}</td>					
					<td>{{ date_format(date_create($bill->trx_date),"d-m-Y")}}</td>
					<td>
						<a href="{{url('/ventas/factura/' .$bill->id)}}"><button class="btn btn-info btn-xs">Editar</button></a>
						@if($bill->balance == $bill->amount && $bill->status_trx != 'CANCEL')
                         				<a href="{{url('/ventas/factura/cancel/' . $bill->customer_trx_id)}}"><button class="btn btn-danger btn-xs">Cancelar</button></a>
                         			@endif
                   				<a href="{{url('/ventas/create/plazo/' . $bill->customer_trx_id)}}"><button class="btn btn-warning btn-xs">Plazos  
                   					<span class="badge">{{$bill->terms->count() > 0 ? $bill->terms->count() : ''}}</span> 
                   				</button></a>                         			
					</td>
				</tr>
				@include('ventas.factura.partials.message')
				@endforeach
			</table>
		</div>
		<div class="text-center">
			{{$bills->appends(Request::only(['client', 'trxStart', 'trxEnd', 'dateStart', 'dateEnd']))->render()}}			
		</div>
	</div>
</div>

@endsection

@section('js')
    <script>
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
            language: "es",
            autoclose: true,
            viewMode: 'years'
        });

    </script>
@endsection